# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=25)),
                ('latt', models.DecimalField(decimal_places=10, max_digits=20)),
                ('long', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
