# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='from_location',
            new_name='from_loc',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='to_location',
            new_name='to_loc',
        ),
    ]
