# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20170315_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='drop_date',
            field=models.DateTimeField(auto_now=True, verbose_name='delivery date'),
        ),
    ]
