# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transfers_drop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='drop_date',
            field=models.DateField(verbose_name='delivery date'),
        ),
    ]
