# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_auto_20170323_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='pick_date',
            field=models.DateField(auto_now=True, verbose_name='return date'),
        ),
    ]
