# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_auto_20170324_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
