# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_hotels_hotel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_address',
            field=models.CharField(default='empty', max_length=45),
            preserve_default=False,
        ),
    ]
